POST /test.php HTTP/1.1
Host: notentabelle.localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: text/plain;charset=UTF-8
Content-Length: 206
Origin: https://notentabelle.localhost
Connection: keep-alive
Referer: https://notentabelle.localhost/app
Cookie: PHPSESSID=l8og8akpupv3qmv6l81a0j4n0j
Pragma: no-cache
Cache-Control: no-cache


[
   

]